/*
 * Auto-generated by scripts/regenerate-coverage-preload.ts. Do not hand-edit;
 * run `bun run scripts/regenerate-coverage-preload.ts` to rewrite.
 *
 * `bun test --coverage` only emits rows for files the runner imports. Untested
 * src/infra, src/composition, and src/presenter files are silently absent
 * from the table — which makes the per-file gate trivially pass. This preload
 * side-effect-imports every such file so they appear at 0% (or better) and
 * the gate can fail loudly.
 *
 * Wired ONLY at coverage time, NOT in bunfig.toml. `scripts/check-coverage.ts`
 * spawns `bun test --coverage --preload ./scripts/coverage-preload.ts`.
 *
 * See skills/atelier/references/workflow.md.
 */
